### ISSUE TITLE
try out the educator jupyter notebook for feedback

### ISSUE THREAD

**Issue by alfredodeza** [microsoft/codespaces-teaching-template-py#11]
Give the repository a try with Codespaces and report any feedback

- Head over to https://github.com/microsoft/codespaces-teaching-template-py/ and go through the README
- Follow the README and create a new Codespace
- Use the example-notebook.ipynb and try out the cells
- Capture inconsistencies and list possible improvements

**Comment by abrilurena** [comment]
This to be modify: 

1. grammar error. Change it to: A **Codespaces is a** development environment that's hosted in the cloud that you can configure.
![image](https://user-images.githubusercontent.com/107883174/189443247-2a1a71fa-c483-4bcf-bd0d-fc7b19491f9f.png)

**2. link doesn't work**
![image](https://user-images.githubusercontent.com/107883174/189443626-c74dca29-8510-4652-bd53-c6ca04b197ce.png)

3. grammar. 

![image](https://user-images.githubusercontent.com/107883174/189444722-723f6516-f66b-40c2-bd63-f07223b2055b.png)

4. Should it be "_the_ extensions" and "_pre-installed_ "? 👀 
Not sure but I just wanted to share this. 
![image](https://user-images.githubusercontent.com/107883174/189445161-c995eab4-ef83-449a-b9f4-ed3bffd382aa.png)

**Comment by PabloNunes** [comment]
Added info to help with the clarity and issues that I found in the guide.
@abrilurena and @alfredodeza, review the grammar and other issues if possible.

**Comment by PabloNunes** [comment]
README improved and tried out. 
Closing Issue until further notice.
