### ISSUE TITLE
Brazilian Portuguese localization

### ISSUE THREAD

**Issue by cyz** [microsoft/codespaces-teaching-template-py#40]
Hi all 👋

We need create a Brazilian Portuguese translation and make sure it is working according to the English content.

Main folder: [https://github.com/education/codespaces-teaching-template-py](https://github.com/education/codespaces-teaching-template-py)

**Please compare each file below to its original in English and if required, please send a PR.**
| File | Status         |
|------|----------------|
| README.md     | pending review |
| example-notebook.ipynb      | pending review |
| slides.pptx    | pending review |

To send the localization, please, create the folder `pt-BR` under  [`translations`](https://github.com/education/codespaces-teaching-template-py/tree/main/translations/).

**Comment by Chikuji** [comment]
Hi @cyz, I'll translate and review this content.

**Comment by Chikuji** [comment]
Hey @cyz, thank you so much!  "#42 the answer to life, universe and everything"
